# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{engen}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh McArthur"]
  s.date = %q{2011-06-03}
  s.description = %q{A gem for Ruby on Rails 3 that adds an engine generator for easy code extension}
  s.email = %q{joshua.mcarthur@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "engen.gemspec",
    "lib/generators/engine/USAGE",
    "lib/generators/engine/engine_generator.rb",
    "lib/generators/engine/templates/Gemfile",
    "lib/generators/engine/templates/engine.gemspec.tt",
    "lib/generators/engine/templates/gitignore.tt",
    "lib/generators/engine/templates/lib/%file_name%.rb.tt",
    "lib/generators/engine/templates/lib/engine.rb.tt",
    "lib/generators/engine/templates/lib/tasks/%file_name%.rake.tt",
    "lib/generators/engine/templates/routes.rb",
    "test/helper.rb",
    "test/test_engen.rb"
  ]
  s.homepage = %q{http://github.com/joshmcarthur/engen}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.0}
  s.summary = %q{Rails 3 Engine Generator}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<git>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<git>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<git>, [">= 0"])
  end
end

